- libs/common/ngx/local-store/src/lib/services/common-ngx-local-store.service.ts
- libs/common/ngx/settings/src/lib/services/common-ngx-settings.service.ts
Removed some lines that lead to a no-op case when updating setting values in client local storage.
The operation was already being performed on setttings service state change.
> Fixed no-op case in common-ngx-settings-service

- libs/maps/esri/src/lib/services/map.service.ts
- libs/ui-kits/ngx/branding/src/lib/reveille-console-log/reveille-console-log.component.html
When a building is specified multiple times in a URL param, the highlight "stacks" so that building is over-highlighted compared to other buildings. E.g. `bldg=ZACH,ZACH,ZACH,CHEN` CHEN has correct highlight, but ZACH has too much:
While I was fixing this, I noticed that `strip` isn't a function, so I changed that to `trim`, fixed a typo in a comment, and removed the "reveille-console-log works!" default comment
> Fix duplicate URL params causing visual glitch

- libs/covid/data-api/src/lib/modules/counties/counties.service.ts
Modifying the "counties/stats/" endpoint to return lockdown information. This is so the map that track lockdowns can easily color code the counties based on lockdowns timestamps.
> Counties api mod

- apps/aggiemap-angular/src/environments/definitions.ts
MSI no longer uses a date stamped basemap service name. The basemap service which was last used by aggiemap was taken down and basically broke it.
Updating the basemap to use the new static named basemap service.
> Updated with date-less basemap url

- apps/aggiemap-angular/src/environments/environment.ts
- libs/maps/feature/layer-list/src/lib/components/layer-list-categorized/layer-list-categorized.component.html
- libs/maps/feature/layer-list/src/lib/components/layer-list/layer-list.component.html
- libs/maps/feature/layer-list/src/lib/components/layer-list/layer-list.component.scss
- libs/maps/feature/layer-list/src/lib/services/layer-list.service.ts
- libs/maps/feature/legend/src/lib/services/legend.service.ts
Not the prettiest implementation but will suffice for now.
Better ways to do this: Layer list is handled by CSS, keeping in mind categorized layer lists and re-rendering on layer store changes. Would be better to handle all of this within the model and let the rendering to the structural directives just like the legend is rendering legend items.
> Esri layer list extent filter

- apps/aggiemap-angular/src/environments/environment.prod.ts
- apps/aggiemap-angular/src/environments/environment.ts
- libs/aggiemap/src/lib/modules/sidebar/sidebar.component.html
- libs/aggiemap/src/lib/modules/sidebar/sidebar.component.ts
- libs/maps/feature/trip-planner/src/lib/components/trip-planner-mode-picker/containers/base/base.component.html
- libs/maps/feature/trip-planner/src/lib/components/trip-planner-mode-picker/containers/base/base.component.ts
- libs/maps/feature/trip-planner/src/lib/components/trip-planner-mode-picker/containers/mobile/mobile.component.html
- libs/maps/feature/trip-planner/src/lib/components/trip-planner-mode-picker/containers/mobile/mobile.component.ts
- libs/maps/feature/trip-planner/src/lib/components/trip-planner-options/components/base/base.component.ts
- libs/maps/feature/trip-planner/src/lib/components/trip-planner-options/components/biking/trip-planner-biking-options.component.html
- libs/maps/feature/trip-planner/src/lib/components/trip-planner-options/components/biking/trip-planner-biking-options.component.ts
- libs/maps/feature/trip-planner/src/lib/components/trip-planner-options/components/parking/trip-planner-parking-options.component.html
- libs/maps/feature/trip-planner/src/lib/components/trip-planner-options/components/parking/trip-planner-parking-options.component.ts
- libs/maps/feature/trip-planner/src/lib/services/trip-planner.service.ts
A building search with the keyword "MIST" which is the building abbreviation for Mitchell Inst for Fundamental Phys & Astronomy building returned instead Bioche*mist*ry/Biophysics Building building. This was caused by a first-order query result as a result of incoming visits from student schedule pages from Howdy.
This implements a secondary scoring where lookup that will consider cases where the the input keyword and scores all results based on the combined results.
Because this will be the first public release of the project based on the new monorepo structure, I have hidden many of the development/experimental features unless they're on a development host.
> fix(aggiemap): additional scoring for building searches

- libs/maps/feature/layer-list/src/lib/services/layer-list.service.ts
Event was emitting layer property state change instead of a collection of layer list items.
> fix(esri-layer-list): Fix incorrect event emission for layer item toggle

- apps/aggiemap-angular/src/polyfills.ts
- apps/bikeshare/src/polyfills.ts
- apps/trees-angular/src/polyfills.ts
- apps/ues-angular/src/polyfills.ts
Use of Array.flat() broke apps on browsers without full support.
> fix(aggiemap): Added array polyfill to aggiemap-based apps

- apps/oidc-admin-angular/src/app/app.component.html
- apps/oidc-admin-angular/src/app/app.component.ts
- apps/oidc-admin-angular/src/environments/environment.ts
- apps/oidc-admin-nest/src/environments/environment.prod.ts
- apps/oidc-admin-nest/src/environments/environment.ts
- apps/oidc-admin-nest/src/main.ts
- apps/oidc-provider-nest/src/app/app.module.ts
- apps/oidc-provider-nest/src/environments/environment.prod.ts
- apps/oidc-provider-nest/src/environments/environment.ts
- apps/oidc-provider-nest/src/main.ts
The applications needed several environment configuration changes and fixes to prepare them for production. Still a few more things to get through but this should put us one step closer:
- IDP Angular application sidebar login now references the environment `api_url`, instead of fixed url.
- Re-added server listening printouts for `oidc-admin-nest` and `oidc-provider-nest` so we can see which port they're running on. It was impossible to tell beforehand.
- Added assets folder and dummy file to `oidc-admin-nest/src` that weren't there before and prevented local serving
- Added production configuration for `oidc-admin-nest` and `oidc-provider-nest` including `port` and `globalPrefix`
> fix(oidc-apps): Production configurations and fixes

- apps/oidc-admin-nest/src/environments/environment.prod.ts
Production environment did not have a db export which caused the build to fail.
> fix(oidc-admin-nest): Added production environment DB config export 

- libs/common/ngx/environment/src/lib/services/environment.service.ts
- libs/common/types/src/lib/common-types.ts
- libs/maps/esri/src/lib/components/esri-map/esri-map.component.ts
- libs/maps/esri/src/lib/services/map.service.ts
- libs/maps/esri/src/lib/services/module-provider.service.ts
- libs/maps/feature/layer-list/src/lib/services/layer-list.service.ts
- libs/maps/feature/legend/src/lib/components/legend/legend.component.html
- libs/maps/feature/legend/src/lib/components/legend/legend.component.scss
- libs/maps/feature/legend/src/lib/components/legend/legend.component.ts
- libs/maps/feature/legend/src/lib/maps-feature-legend.module.ts
- libs/maps/feature/legend/src/lib/services/legend.service.ts
- libs/ui-kits/ngx/layout/structural/src/index.ts
- libs/ui-kits/ngx/layout/structural/src/lib/directives/element-insert/element-insert.directive.spec.ts
- libs/ui-kits/ngx/layout/structural/src/lib/directives/element-insert/element-insert.directive.ts
- libs/ui-kits/ngx/layout/structural/src/lib/ui-kits-ngx-layout-structural.module.ts
Legend component now uses Esri's legend view model which adds the ability to render the symbol previews. This will remove the necessity to manually include all of the application's legend items in the environments. However, there will be some issues in other applications in which legend overrides. However services which do not have correct renderers for which we have provided overrides. For example Aggiemap buildings legend item is transparent from the service, and a replacement is provided in the legend. These legend items will be rendered as-is using the legend view model preview property, but we'll need to assimilate some of the old service logic to allow legend item overrides.
Example:
Currently, the legend component only supports `SymbolTableElement`'s.
> refactor(maps-feature-legend): Esri legend component rewrite

- libs/aggiemap/src/lib/popups/components/base-directions/base-directions.component.html
- libs/common/types/src/lib/common-types.ts
- libs/maps/esri/src/lib/services/map.service.ts
- libs/maps/feature/popup/src/lib/services/popup.service.ts
Depends on #103 
While the esri doc's state that the group layer constructor can auto-cast layers, this has not been the case with the current version of the arcgis js api. I tested with newer versions and the same remains true. So the Esri map service now correctly processes layer sources with type `group`.
> refactor(maps-esri): Map service group layer source auto-cast support

- apps/aggiemap-angular/src/environments/definitions.ts
- libs/maps/feature/legend/src/lib/components/legend/legend.component.html
- libs/maps/feature/legend/src/lib/components/legend/legend.component.scss
- libs/maps/feature/legend/src/lib/components/legend/legend.component.ts
- libs/maps/feature/legend/src/lib/services/legend.service.ts
Static legend items: these are items that are not added on to the map as a layer and thus cannot have a legend info rendered automatically for it, but need to represented in the legend.
Aggiemap has some of these because the entire map server is not used as a source and certain elements are not treated as features and are not interactable.
Also updated Aggiemap definitions to remove deprecated options.
> fix(maps-feature-legend): Re-added support for static legend items

- nx.json
- workspace.json
`ues-sass` lib was outside of the projects dictionary in workspace.json.
Also added in nx.json because it was missing completely causing workspace and nx JSON files to be out of sync.
> fix(nx-workspace): Fixed ues-sass lib definition format error

- libs/common/ngx/auth/src/lib/services/auth-interceptor.service.ts
- libs/common/ngx/auth/src/lib/services/auth.service.ts
The auth service now cleans the auth URL before making XHR requests or redirecting to prevent 404 routing issues due to a malformed URL (double slash between host name and route name).
Example: https://domain.com//route/to/resource
> fix(ngx-auth): Fixed auth redirection sensitivity

- .prettierrc
- azure-pipelines.yml
Added conditional affected base that correctly sets the `base` for nx commands so that builds calculate calculate changes correctly and avoid the case where `head` and `target` are the same on `development` branch.
Added production stage dependency on development since if development does not build, neither should production. Both use the same build options, just different configs.
Added tag assignment stage depedency on development and production since both  must pass for any release trigger.
This PR was initially only added a condition on the Dev build stage that prevented builds from running on `development` or `master` branches. However, this would cause PR merges to never be tested and the CI checks would be missing from github commit history. The goal of the PR changed to come up …
> ci: Added  conditional affected base variable for nx commands

- libs/common/types/src/lib/common-types.ts
- libs/common/utils/geometry/esri/src/lib/common-utils-geometry-esri.ts
- libs/cpa/common/ngx/src/lib/modules/forms/components/participant/participant.component.ts
- libs/maps/esri/src/lib/services/map.service.ts
- libs/maps/esri/src/lib/services/module-provider.service.ts
- libs/maps/feature/forms/src/lib/components/layer-configuration/layer-configuration.component.ts
- libs/maps/feature/legend/src/lib/components/legend-element/legend-element.component.html
- libs/maps/feature/legend/src/lib/components/legend-element/legend-element.component.scss
The snapshot builder and participant component now support map image layer types with raster sources. 
The change extends deeper into the map service to support layer source auto-casting.
> feat(cpa-angular): Map image layer support

- apps/oidc-provider-nest/src/main.ts
- libs/oidc/common/src/lib/services/client-metadata/client-metadata.service.ts
When using the `-s` flag and providing the default values would sometimes create a race condition where some necessary steps had not completed executing (db insertions) before other subsequent steps did.
Also setup now waits on previous steps to complete before proceeding to the next.
> fix(oidc-provider-nest): Fix OIDC provider race condition on defaults setup

- apps/ues-recycling-angular/src/environments/environment.prod.ts
- azure-pipelines.yml
- workspace.json
Integrated the CPA website and API into the CI/CD system by setting up a deployment pipeline in Azure and by modifying the CI Yaml to remove the applications from the ignore list. Also added the assets section to the CPA API section on the workspace JSON, and edited the production environment file for ues-recycling-angular to have the correct API url.
> ci: Included CPA projects in the ci pipeline

- libs/cpa/common/entities/src/lib/base/all.entity.ts
- libs/cpa/data-api/src/lib/modules/workshops/workshops.service.ts
Old logic was causing different order snapshots for a workshop on an update due to a promise race condition when inserting snapshots for a workshop.
New logic passes on the saving responsibility to the ORM which in fact preserves the correct order for snapshots.
> refactor(cpa): Refactored snapshot setting logic

- libs/assets/batch/startup.bat
Created a startup.batch file in the monorepo which contains the start-up procedure for NSSM. Modified said procedure to query if PM2 was already running, and if so don't attempt to resurrect. This was done to mitigate an issue with the resurrect command in which it was stuck in a infinite loop crashing/slowing down the server.
>  ci: PM2 launch on windows start-up via NSSM, as well as restart if crash. 

- .gitignore
- apps/oidc-provider-nest/src/main.ts
- libs/oidc/common/src/lib/utils/email/mailer.util.ts
Requires a `mailerconfig.ts` file in the environments directory with an exported member like:
`export const mailerConfig = {
user: string (email you've setup Google API for,
accessToken: string,
clientId: string,
clientSecret: string,
refreshToken: string
};`
You'll need to go through some steps to setup `mailerConfig` for your own email or I can show you it in action with mine.
> feat(oidc-provider-nest): NodeMailer can now use Gmail to send emails

- apps/oidc-admin-nest/src/app/app.module.ts
- apps/oidc-client-test/src/environments/oidcconfig.ts
- apps/oidc-provider-nest/src/app/app.module.ts
- apps/oidc-provider-nest/src/main.ts
- libs/oidc/client/src/lib/auth/oidc-client.controller.ts
- libs/oidc/common/src/lib/entities/all.entity.ts
- libs/oidc/common/src/lib/modules/client-metadata/client-metadata.module.ts
- libs/oidc/common/src/lib/services/client-metadata/client-metadata.service.ts
Enabled back channel logout support. 
Required adding some additional logic to the yargs initialization system as well as some additions to the mega client-metadata.service class. 
Added an additional route to the oidc-client lib which will logout the user.
> feat(oidc-provider / oidc-client): Support for back channel logout

- .vscode/settings.json
Path was invalid in OSX environments which prevented tslint from starting up correctly.
Fixed path works on both OSX and Windows.
> fix(workspace): Updated the workspace typescript library path

- apps/oidc-admin-angular/src/app/app.module.ts
- apps/ues-angular/src/app/app.component.ts
- apps/ues-angular/src/app/app.module.ts
- apps/ues-effluent-angular/src/app/app.module.ts
- apps/ues-recycling-angular/src/app/app.module.ts
- apps/ues-valves-angular/src/app/app.module.ts
- libs/common/ngx/auth/src/lib/guards/auth.guard.ts
- libs/common/ngx/auth/src/lib/services/auth-interceptor.service.ts
- libs/common/ngx/auth/src/lib/services/auth.service.ts
- libs/ues/common/ngx/src/lib/modules/auth/auth.module.ts
- libs/ues/common/ngx/src/lib/modules/auth/pages/session-expired/session-expired.component.html
- libs/ues/common/ngx/src/lib/modules/auth/pages/session-expired/session-expired.component.scss
- libs/ues/common/ngx/src/lib/modules/auth/pages/session-expired/session-expired.component.spec.ts
- libs/ues/common/ngx/src/lib/modules/auth/pages/session-expired/session-expired.component.ts
- libs/ues/common/ngx/src/lib/modules/auth/pages/session-expired/session-expired.module.ts
- libs/ues/common/ngx/src/lib/modules/routing/routing.module.ts
Introduces a "session expired" route that can be navigated to manually or automagically by auth guards to present the user with a pre-login instruction prompt. In the case of UES operations, it is used to remind users to use certain credentials in the login process.
> feat(ues-operations): Auth prompt routes

- libs/assets/batch/startup.bat
Added a loop that is set on five minute intervals to the startup batch file for the PM2 window service that allows for NSSM to monitor whether or not PM2 has crashed. If PM2 has crashed it will attempt to resurrect and will publish an event in the logs entitled "nssmCheck".
> ci: Added a loop and event scenario if PM2 crashes to startup.bat file

- apps/oidc-provider-nest/src/main.ts
- libs/oidc/common/src/lib/oidc-common.ts
- libs/oidc/common/src/lib/utils/email/mailer.util.ts
https://it.tamu.edu/services/email-messaging-and-collaboration/campus-email-services/mail-relay-resources/#service-service-details
Added this provider to nodemailer. Works when you ignore TLS in nodemailer options and use port 25. Must be connected to TAMU VPN.
> feat(oidc-provider): Added TAMU smtp-relay support for nodemailer

- libs/ues/common/ngx/src/lib/modules/routing/routing.module.ts
Will now once again automatically and immediately redirectto to MS login when a user's session is expired/non-existent.
All the redirection logic and views are still in the code base should they need to be used again in the future.
> feat(ues-angular): Removed the session expired view

- libs/maps/feature/popup/src/lib/containers/mobile/mobile.component.html
The popup container should not be visible at all unless there is a component to render.
Fixes #152
> fix(aggiemap-angular): Fixed the mobile popup initial visibility

- libs/aggiemap/src/lib/popups/components/building/building-popup.component.ts
Now points to the root URL of the website. Proctors website is undergoing changes and does not currently support linking to individual buildings.
> fix(aggiemap-angular): Updated building popup proctor button URL

- libs/aggiemap/src/lib/modules/mobile-ui/animations/elements.ts
- libs/aggiemap/src/lib/modules/mobile-ui/components/omnisearch/omnisearch.component.scss
- libs/aggiemap/src/lib/modules/mobile-ui/components/omnisearch/omnisearch.component.ts
Now applies initial display properties so that the backdrop is hidden on init state and sequentially applies an initial display property to show the backdrop before the animation is started. This preserves the original animation while preventing user scrolling when using a page element to scroll.
Fixes #155
> fix(aggiemap-angular): Fixed mobile search backdrop overflow

- apps/gisday-competitions-angular/src/app/modules/routing/routing.module.ts
- apps/gisday-competitions-angular/src/environments/environment.prod.ts
- apps/gisday-competitions-angular/src/environments/environment.ts
Fixed GIS Day user authentication redirects on localhost due to a change in the parent application hostname.
> fix(gisday-angular-competitions): Fixed authentication flow

- azure-pipelines.yml
Removed production dependsOn development build condition. This reduced the ability to parallelize jobs correctly causing super long build times.
> ci: Improved main pipeline job run parallelization

- apps/oidc-admin-nest/src/package.json
- apps/oidc-provider-nest/src/package.json
Affects:
- oidc-admin-nest
- oidc-provider-nest
Updated nodemailer version to latest non-vulnerable on the deployment package.json's and also pinned the version
Addresses CVE-2021-23400
https://github.com/TamuGeoInnovation/Tamu.GeoInnovation.js.monorepo/security/dependabot/9
> chore(deps): Bumped and pinned nodemailer for deployment apps

- azure-pipelines.yml
- templates/jobs/build.yml
- templates/jobs/buildTags.yml
Excluded projects list is now passed down from entry yaml instead of residing in many files. This prevents desync between the various files as projects are added/removed from the exclusion list.
> feat(ci): Centralize Nx excluded projects

- templates/jobs/build.yml
Removes the need to create a copy files task for every new app or every app that should be built. App config secrets now only need to be stored in the same file structure and copy files task will take care of putting all the files in the right place.
Some general variable casing fixups  as well included.
> feat(ci): Secrets file copy optimization

- .vscode/settings.json
Removes the workspace tsdk path which is no longer necessary and in some cases might cause issues with the angular language service
> chore: Workspace setting update (vscode.tsdk)

- libs/ui-kits/ngx/forms/src/lib/models/abstract-value-accessor-form/abstract-value-accessor-form.component.ts
Inadvertently removed onChange and onTouched calls when a value is being set. This means that the UI does not report to the model when changes are made.
Regression introduced in: #208
> fix: Fixed custom control value accessor regression

- libs/oidc/ngx/.eslintrc.json
- libs/oidc/ngx/README.md
- libs/oidc/ngx/jest.config.js
- libs/oidc/ngx/project.json
- libs/oidc/ngx/src/index.ts
- libs/oidc/ngx/src/lib/modules/auth-redirect/auth-routing.component.html
- libs/oidc/ngx/src/lib/modules/auth-redirect/auth-routing.component.spec.ts
- libs/oidc/ngx/src/lib/modules/auth-redirect/auth-routing.component.ts
- libs/oidc/ngx/src/lib/modules/auth-redirect/auth-routing.module.ts
- libs/oidc/ngx/src/lib/modules/auth-redirect/components/login-post/login-post.component.html
- libs/oidc/ngx/src/lib/modules/auth-redirect/components/login-post/login-post.component.spec.ts
- libs/oidc/ngx/src/lib/modules/auth-redirect/components/login-post/login-post.component.ts
- libs/oidc/ngx/src/test-setup.ts
- libs/oidc/ngx/tsconfig.json
- libs/oidc/ngx/tsconfig.lib.json
- libs/oidc/ngx/tsconfig.spec.json
- tsconfig.base.json
- workspace.json
Adds common  PnP routes for angular applications utilizing the `angular-auth-oidc-client`.
Details in lib README
> feat:(oidc-ngx): Angular OIDC Flow Common Routes

- libs/oidc/common/src/lib/entities/all.entity.ts
- Updated all entities used by oidc-provider that had data properties to have a length of MAX instead of max.
> fix(oidc): Fixed data field getting set to NULL on deployment

- libs/common/nest/environment/.babelrc
- libs/common/nest/environment/.eslintrc.json
- libs/common/nest/environment/README.md
- libs/common/nest/environment/jest.config.js
- libs/common/nest/environment/project.json
- libs/common/nest/environment/src/index.ts
- libs/common/nest/environment/src/lib/environment.module.ts
- libs/common/nest/environment/src/lib/services/environment/environment.service.spec.ts
- libs/common/nest/environment/src/lib/services/environment/environment.service.ts
- libs/common/nest/environment/src/lib/tokens/environment.token.ts
- libs/common/nest/environment/tsconfig.json
- libs/common/nest/environment/tsconfig.lib.json
- libs/common/nest/environment/tsconfig.spec.json
- tsconfig.base.json
- workspace.json
This is the NestJS counterpart of the existing Angular environment service that allows registering environment variables in a single place and having them accessible through a service for apps/libs.
> feat: Environment access library for NestJS apps/libs

- libs/oidc/common/README.md
- libs/oidc/common/src/index.ts
- libs/oidc/common/src/lib/guards/jwt/jwt.guard.spec.ts
- libs/oidc/common/src/lib/guards/jwt/jwt.guard.ts
- libs/oidc/common/src/lib/modules/auth/auth.module.ts
- libs/oidc/common/src/lib/modules/tokens/jwks_url.token.ts
- libs/oidc/common/src/lib/strategies/jwt/jwt.strategy.spec.ts
- libs/oidc/common/src/lib/strategies/jwt/jwt.strategy.ts
- package-lock.json
- package.json
Implements a generic authentication module that can be applied to existing nestjs applications. Exposes a JWT auth guard that validates a request's bearer JWT against a public key endpoint. 
Documentation on the root of the library.
libs\oidc\common\README.md
> feat(oidc-common): JWT auth module

- libs/oidc/provider/src/lib/services/provider/provider.service.ts
Per documentation:
https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#trusting-tls-offloading-proxies
This fixes the OIDC well-known protocol from "http" => in "https" in urls which ultimately fixes authentication errors due to mixed content when the initiator originates from an https site and the client follows the http URL instead.
> fix(oidc-provider): Enabled TLS offloading proxy trust

- apps/oidc-provider-nest/src/assets/views/interaction.ejs
- libs/oidc/provider/src/lib/controllers/interaction/interaction.controller.ts
The consent prompt from the IdP was... lacking. I've updated it to use the styled "parent" view `_layout-simple.ejs` to give it some visual flair.
> feat(oidc-provider): Consent prompt styling

- templates/tasks/cacheOrRestoreDependencies.yml
Latest LTS version of Node as of this PR is 16.15.1 which updates NPM to 8.11.0 which causes `npm ci` to fail with an error suggesting `package.json` and `package-lock.json` are out of sync.
Last known working version of Node that includes a working version of NPM is 16.15.0 and has been pinned in the cache dep task until the issue is resolved upstream.
> ci: Pinned Node version to 16.15.0 which fixes npm ci failure in dep cache task

- apps/aggiemap-angular/src/environments/definitions.ts
- libs/maps/feature/trip-planner/src/lib/services/transportation/drive/parking.service.ts
- libs/maps/feature/trip-planner/src/lib/services/trip-planner.service.ts
Depends on #243 
At some point the transportation services deprecated some old map services that Aggiemap relied on to generate a list of parking passes under the driving routing options. The list is now working, and as a consequence the permit setting feature is also working. 
Furthermore, when generating a route that generated more than one routing task (e.g. driving with a permit selected where the first task is the route start point to a parking lot/garage, and the second task is from the parking lot/garage to the final destination) caused the trip planning service to fail to calculate and draw the route due to the API update. This has also been fixed and multi-modal routing works once again.
> fix(aggiemap-angular): Fix driving travel options and multi-modal routing

- libs/cpa/ngx/data-access/src/lib/services/participant/participants.service.spec.ts
- libs/cpa/ngx/data-access/src/lib/services/response/response.service.spec.ts
- libs/cpa/ngx/data-access/src/lib/services/scenario/scenario.service.spec.ts
- libs/cpa/ngx/data-access/src/lib/services/snapshot/snapshot.service.spec.ts
- libs/cpa/ngx/data-access/src/lib/services/workshop/workshop.service.spec.ts
The following PR was for getting back into the groove of testing. Establishing how to test services with dependencies on other services and Http Client. 
1. Create a skeleton mock. 
`const spyForDependentService= { someFunction: jest.fn() }`
2. In the beforeEach establish the providers array:
```
beforeEach(() => {
TestBed.configureTestingModule({
providers: [
ServiceToBeTested,
{
provide: DependentService,
useValue: spyForDependentService
}
]
});
});
```
3. If the logic of the service has different actions based on a value condition of the dependent service, don't inject the service being tested in the beforeEach configureTestingModule statement. Instead inject it in the individual test cases after mocking the return value for said dependent services function call. 
1. Import …
> testing(CPA): Unit tests added for CPA lib data-access services. 

- apps/mailroom-nest/README.md
- apps/mailroom-nest/src/app/app.controller.ts
Made it so mailroom-nest can utilize multipart/form-data, json encoded, and url encoded bodies. Fixes issue #254.
> fix(mailroom-nest): Fixed routes used to send emails

- apps/oidc-provider-nest/project.json
- apps/oidc-provider-nest/src/package.json
The auto-generated version did not have pinned versions which was causing an initialization error due to a breaking change in one of the dependencies.
This is a recurring issue with some deployments and the ultimate solution is coming up with a script that goes through the package-lock tree and picks out all pinned dependency versions or better yet, creates a `package-lock.json` from the root package-lock.json otherwise we're going to keep getting non-deterministic builds between development machines and deployment environments.
> fix(oidc-provider-nest): Added manual package.json for deployments

- apps/mailroom-nest/src/environments/environment.dev.ts
- apps/mailroom-nest/src/environments/environment.prod.ts
- apps/mailroom-nest/src/environments/environment.ts
- apps/mailroom-nest/src/main.ts
- libs/oidc/common/src/lib/utils/email/mailer.util.ts
Changed the code to use `relay.tamu.edu` or `smtp-relay.tamu.edu` based on an environment value. We should now be able to use `mailroom-nest` in the dev VM whereas before it didn't work because it was not a part of the TAMU network (or something like that).
> feat(mailroom-nest): mailroom-nest now should work on dev vm

- libs/mailroom/data-api/.babelrc
- libs/mailroom/data-api/.eslintrc.json
- libs/mailroom/data-api/README.md
- libs/mailroom/data-api/jest.config.js
- libs/mailroom/data-api/project.json
- libs/mailroom/data-api/src/lib/email/email.controller.spec.ts
- libs/mailroom/data-api/src/lib/email/email.controller.ts
- libs/mailroom/data-api/src/lib/email/email.module.ts
- libs/mailroom/data-api/src/lib/email/email.service.spec.ts
- libs/mailroom/data-api/src/lib/email/email.service.ts
- libs/mailroom/data-api/tsconfig.json
- libs/mailroom/data-api/tsconfig.lib.json
- libs/mailroom/data-api/tsconfig.spec.json
- tsconfig.base.json
- workspace.json
Initial boilerplate for the creation of the mailroom/data-api lib; addresses https://github.com/TamuGeoInnovation/Tamu.GeoInnovation.js.monorepo/pull/260#discussion_r927715410. As this is just a boiler plate PR no implementation is included.
> feat(mailroom-data-api): Added mailroom data-api lib

- libs/aggiemap/ngx/popups/src/lib/components/building/building-popup.component.html
The building department list that appeared on the building popup component has been removed until further notice. 
Addresses #273
> chore(aggiemap-angular): Remove building departments list from popup

- libs/aggiemap/ngx/core/src/lib/pages/map/map.component.ts
- libs/aggiemap/ngx/core/src/lib/pages/map/map.module.ts
- libs/aggiemap/ngx/ui/desktop/src/lib/modules/sidebar/sidebar.component.html
- libs/aggiemap/ngx/ui/shared/src/index.ts
- libs/aggiemap/ngx/ui/shared/src/lib/modules/experiments/components/basemap-override/basemap-override.component.html
- libs/aggiemap/ngx/ui/shared/src/lib/modules/experiments/components/basemap-override/basemap-override.component.scss
- libs/aggiemap/ngx/ui/shared/src/lib/modules/experiments/components/basemap-override/basemap-override.component.spec.ts
- libs/aggiemap/ngx/ui/shared/src/lib/modules/experiments/components/basemap-override/basemap-override.component.ts
- libs/aggiemap/ngx/ui/shared/src/lib/modules/experiments/components/experiments-list/experiments-list.component.html
- libs/aggiemap/ngx/ui/shared/src/lib/modules/experiments/components/experiments-list/experiments-list.component.scss
- libs/aggiemap/ngx/ui/shared/src/lib/modules/experiments/components/experiments-list/experiments-list.component.spec.ts
- libs/aggiemap/ngx/ui/shared/src/lib/modules/experiments/components/experiments-list/experiments-list.component.ts
- libs/aggiemap/ngx/ui/shared/src/lib/modules/experiments/experiments.module.ts
Adds "experiments" sidebar tab that hosts a single component: basemap override which supports the function to replace the rendered basemap. 
Is only visible in development environments.
Addresses #271
> feat(aggiemap-angular): Support ability to override rendered basemap

- libs/aggiemap/ngx/core/src/lib/pages/map/map.component.ts
Really silly bug that leads to trying to access a property of an non-object variable.
This is why we are supposed to review things, and not just hit the merge button.
> fix(aggiemap-angular): Fix local store settings object destructuring

- libs/ui-kits/ngx/layout/modal/src/lib/components/modal-host/modal-host.component.scss
Mobile:
Mid-size:
Desktop:
Resolves #272
> fix(ui-kits-ngx-modal): Responsive layout improvements

- libs/aggiemap/ngx/core/src/lib/pages/map/map.component.html
Use of angular application testing service to remove the perspective toggle component from production environments.
Resolves #283
> fix(aggiemap-angular): Perspective toggle only shows up in testing environments
