- apps/angular-aggiemap-trees/src/app/app.component.ts
> Fix missing "public" in aggiemap-trees app component

- libs/common/ngx/environment/src/lib/services/environment.service.spec.ts
- libs/common/ngx/local-store/src/lib/common-ngx-local-store.module.spec.ts
- libs/common/ngx/local-store/src/lib/services/common-ngx-local-store.service.spec.ts
- libs/common/ngx/settings/src/lib/services/common-ngx-settings.service.spec.ts
- libs/common/ngx/settings/src/lib/services/common-ngx-settings.service.ts
- libs/search/src/lib/services/search.service.spec.ts
- libs/ui-kits/ngx/forms/src/lib/components/select/select.component.spec.ts
- libs/ui-kits/ngx/forms/src/lib/components/select/select.component.ts
This is a long running effort, but this is a reasonable point to check-in changes
> Increase test coverage

- libs/two/data-api/src/lib/modules/data/data.controller.ts
Fixed issue where data returned was out of order, causing chicken scratch line charts
> Fixed two nest data api endpoints

- apps/aggiemap-angular/src/environments/definitions.ts
- apps/aggiemap-angular/src/environments/environment.prod.ts
- apps/aggiemap-angular/src/environments/environment.ts
- apps/bikeshare/src/app/components/date-picker/date.component.ts
- apps/bikeshare/src/app/components/map/map.component.html
- apps/bikeshare/src/app/components/map/map.component.spec.ts
- apps/bikeshare/src/app/components/map/map.component.ts
- apps/bikeshare/src/environments/environment.prod.ts
- apps/bikeshare/src/environments/environment.ts
- libs/common/types/src/lib/common-types.ts
- libs/common/types/tsconfig.json
Improved LayerSource typings that allow property entry to some of the more common auto-castable Esri Classes.
> Typing updates

- apps/aggiemap-angular/src/app/modules/routing/app-routing.module.ts
- apps/aggiemap-angular/src/environments/definitions.ts
Added app-wide wildcard route.
Need to make auto-basemap selection
> Updated basemap to BaseMap_20200123

- libs/covid/data-api/src/lib/modules/counties/counties.service.ts
- libs/covid/data-api/src/lib/modules/lockdowns/lockdowns.service.ts
added functionality to the stats endpoint in order to use the endpoint to create a more effective map for the covid data collection team.
> Sites api addition

- apps/trees-angular/src/app/components/map/map.component.ts
- apps/trees-angular/src/environments/definitions.ts
Merging this into development to synchronize all of the child feature branches up to date.
This is pre-req.
> Updated basemap to the permanent one

- apps/ues-angular/src/environments/definitions.ts
Changed UES ArcGIS server url to fix immediate CORS issue due to an updated certificate not including the old host.
> UES CORS Hotfix

- apps/aggiemap-angular/src/app/map/esri-map.component.html
- apps/aggiemap-angular/src/app/map/esri-map.component.ts
- apps/aggiemap-angular/src/environments/definitions.ts
- apps/aggiemap-angular/src/styles.scss
- libs/aggiemap/src/lib/popups/components/building/building-popup.component.html
- libs/ui-kits/ngx/interactions/draggable/src/lib/directives/drag/drag.directive.ts
The old aggiemap repository had some bug fixes and implemented that had not been carried over to the aggiemap application in this repository. This is an import of those changes that work in conjunction with the monorepo structure.
See commits for details.
> bugfix(aggiemap): Import pending bugfixes from old project

- angular.json
- apps/ues-angular/src/environments/definitions.ts
- apps/ues-angular/src/environments/environment.prod.ts
- apps/ues-angular/src/environments/environment.ts
Added new layers to the electrical category for the UES Angular application. 
Also retro-actively applied a configuration setting that enables CORS support on Safari browsers, else the application fails to load entirely.
> feat(ues-angular): UES electrical layer additions

- libs/maps/feature/trip-planner/src/lib/components/trip-planner-options/containers/base/base.component.html
- libs/maps/feature/trip-planner/src/lib/components/trip-planner-options/containers/base/base.component.scss
- libs/maps/feature/trip-planner/src/lib/components/trip-planner-options/containers/base/base.component.ts
> feat(aggiemap-angular): Added return icon and link from routing options pane

- apps/aggiemap-angular/src/index.html
- apps/bikeshare/src/index.html
- apps/cpa-angular/src/index.html
- apps/gisday-competitions-angular/src/index.html
- apps/signage-angular/src/index.html
- apps/trees-angular/src/index.html
- apps/ues-angular/src/index.html
- apps/ues-effluent-angular/src/index.html
- package-lock.json
- package.json
Loads ArcGIS JS API 4.13  instead of 4.12 which was suddenly causing module resolution errors.
> dep(esri-loader): Updated esri-loader npm module

- apps/oidc-admin-angular/src/app/app.module.ts
- apps/oidc-admin-angular/src/environments/environment.prod.ts
Updated the api url for production
> fix(oidc-admin-angular): Fixed missing required HttpClientModule

- apps/ues-angular/src/environments/definitions.ts
- libs/ues/common/ngx/src/lib/modules/map/map.component.html
These changes take advantage of the updated layer list and legend. The categories and layers are pulled directly from the map server endpoint, where previously all layers and categories were manually defined in environments.
> fix(ues-angular): Updated UES Operations map definitions

- libs/ues/effluent/ngx/src/lib/modules/map/map.component.ts
Layer list service was updated and the method no longer exists. Caused error building application.
This however results in the layer list rendering all sampling zones by `zone-id` identifier and not by the result category (positive, negative, inconclusive). This will require including support for mixed legend items, including static and dynamic.
> fix(ues-effluent): Fixed effluent render generation due to deprecated layer list call

- apps/ues-angular/src/environments/environment.prod.ts
- apps/ues-effluent-angular/src/environments/environment.prod.ts
- apps/ues-recycling-angular/src/environments/environment.prod.ts
- apps/ues-valves-angular/src/environments/environment.prod.ts
What: Modified the Angular env files for UES applications
Why: Remove Node refrence 
How: node changes to UES.
> ci(ues): Edited ENV files for UES applications

- apps/ues-angular/src/environments/environment.prod.ts
- apps/ues-effluent-angular/src/environments/environment.prod.ts
- apps/ues-recycling-angular/src/environments/environment.prod.ts
- apps/ues-valves-angular/src/environments/environment.prod.ts
Updated the Env files to reference the correct API URL
>  ci(ues): Edited ENV files for UES applications

- libs/cpa/admin/src/lib/pages/scenarios/common/components/scenario-builder/scenario-builder.component.ts
- libs/cpa/common/entities/src/lib/base/all.entity.ts
- libs/cpa/common/ngx/src/lib/modules/forms/components/participant/participant.component.ts
- libs/cpa/data-api/src/lib/modules/workshops/workshops.service.ts
> fix(cpa): Short fixes for cpa nest and angular

- libs/assets/powershell/pm2_process.ps1
Added a check in the pm2_process.ps1 file that checks for whether or not PM2 exists as a windows service, and if not throws a more informative error.
> ci: Add check for verifying PM2 installed as a service. 

- libs/aggiemap/src/lib/popups/components/lactation/lactation.component.html
Linking directly to lactation room information table.
> fix(aggiemap-angular): Updated lactation poi popup addtl info link

- apps/aggiemap-angular/src/environments/environment.dev.ts
- jobs/build.yml
- jobs/buildTags.yml
The following PR is focused on integrate the AggieMap Application  CI/CD pipeline.
This was done via:
Creating development environment files.
Removing the application from the NX ignore list on the build and tagging job yaml files.
> ci: Integrated AggieMap into the CI/CD pipeline. 

- apps/gisday-competitions-nest/.eslintrc.json
- apps/gisday-competitions-nest/jest.config.js
- apps/gisday-competitions-nest/src/app/app.controller.spec.ts
- apps/gisday-competitions-nest/src/app/app.controller.ts
- apps/gisday-competitions-nest/src/app/app.module.ts
- apps/gisday-competitions-nest/src/app/app.service.spec.ts
- apps/gisday-competitions-nest/src/app/app.service.ts
- apps/gisday-competitions-nest/src/environments/environment.prod.ts
- apps/gisday-competitions-nest/src/environments/environment.ts
- apps/gisday-competitions-nest/src/main.ts
- apps/gisday-competitions-nest/tsconfig.app.json
- apps/gisday-competitions-nest/tsconfig.json
- apps/gisday-competitions-nest/tsconfig.spec.json
- jest.config.js
- libs/gisday/competitions/.eslintrc.json
- libs/gisday/competitions/README.md
- libs/gisday/competitions/jest.config.js
- libs/gisday/competitions/src/index.ts
- libs/gisday/competitions/src/lib/gisday-competitions.module.ts
- libs/gisday/competitions/tsconfig.json
- libs/gisday/competitions/tsconfig.lib.json
- libs/gisday/competitions/tsconfig.spec.json
- nx.json
- tsconfig.base.json
- workspace.json
Includes boilerplate generation for:
- app/gisday-competitions-nest
- libs/gisday/competitions
> feat(gisday-competitions-nest): Boilerplate generation

- libs/common/ngx/pipes/src/lib/parsing/markdown-parse.pipe.ts
- libs/kissingbugs/ngx/src/lib/modules/core/pages/contact/contact.component.html
- libs/kissingbugs/ngx/src/lib/modules/core/pages/contact/contact.component.ts
- libs/kissingbugs/ngx/src/lib/modules/core/pages/faq/faq.component.ts
- libs/kissingbugs/ngx/src/lib/modules/core/pages/map/map.component.ts
- libs/kissingbugs/ngx/src/lib/modules/core/pages/resources/resources.component.ts
- libs/kissingbugs/ngx/src/lib/modules/core/pages/team/team.component.ts
- libs/kissingbugs/ngx/src/lib/modules/core/types/types.ts
- Added Knowledge single-type to replace Resources (fixes name conflict issue)
- Includes Edgar's fix to markdown parse pipe
- Fixed Contact date input max value
> fix(kissingbugs-angular): Added Knowledge single-type

- package-lock.json
This was left out of the previous PR.
> chore: Nx 13 Package Lock Update

- apps/aggiemap-angular/src/assets/directory.html
Static web page that links to links to most past 2d/3d applications for ease of access.
> feat(aggiemap): Add application directory index

- package-lock.json
> chore(deps): Bump ansi-regex from 3.0.0 to 3.0.1

- libs/ui-kits/ngx/layout/modal/.eslintrc.json
- libs/ui-kits/ngx/layout/modal/README.md
- libs/ui-kits/ngx/layout/modal/jest.config.js
- libs/ui-kits/ngx/layout/modal/project.json
- libs/ui-kits/ngx/layout/modal/src/index.ts
- libs/ui-kits/ngx/layout/modal/src/lib/components/modal-host/modal-host.component.html
- libs/ui-kits/ngx/layout/modal/src/lib/components/modal-host/modal-host.component.scss
- libs/ui-kits/ngx/layout/modal/src/lib/components/modal-host/modal-host.component.spec.ts
- libs/ui-kits/ngx/layout/modal/src/lib/components/modal-host/modal-host.component.ts
- libs/ui-kits/ngx/layout/modal/src/lib/services/modal-ref/modal-ref.service.spec.ts
- libs/ui-kits/ngx/layout/modal/src/lib/services/modal-ref/modal-ref.service.ts
- libs/ui-kits/ngx/layout/modal/src/lib/services/modal/modal.service.spec.ts
- libs/ui-kits/ngx/layout/modal/src/lib/services/modal/modal.service.ts
- libs/ui-kits/ngx/layout/modal/src/lib/tokens/modal.tokens.ts
- libs/ui-kits/ngx/layout/modal/src/lib/ui-kits-ngx-layout-modal.module.ts
- libs/ui-kits/ngx/layout/modal/src/test-setup.ts
- libs/ui-kits/ngx/layout/modal/tsconfig.json
- libs/ui-kits/ngx/layout/modal/tsconfig.lib.json
- libs/ui-kits/ngx/layout/modal/tsconfig.spec.json
- tsconfig.base.json
- workspace.json
Enables easy creation of modal card-style windows/prompts.
System details in the lib README.
> feat: Angular modal UI system

- libs/cpa/ngx/admin/src/lib/cpa-ngx-admin.component.html
- libs/cpa/ngx/admin/src/lib/pages/export/export.component.html
- libs/cpa/ngx/admin/src/lib/pages/export/export.component.ts
- libs/cpa/ngx/admin/src/lib/pages/scenarios/common/components/scenario-builder/scenario-builder.component.html
- libs/cpa/ngx/admin/src/lib/pages/scenarios/common/components/scenario-builder/scenario-builder.component.ts
- libs/cpa/ngx/admin/src/lib/pages/snapshots/common/components/snapshot-builder/snapshot-builder.component.html
- libs/cpa/ngx/admin/src/lib/pages/snapshots/common/components/snapshot-builder/snapshot-builder.component.ts
- libs/cpa/ngx/viewer/src/lib/services/viewer.service.ts
Snapshots and scenario builders now have a much improved extent set, update, and reset experience.
> feat(cpa-angular): Added extent set/reset feedback

- apps/oidc-provider-nest/src/environments/environment.dev.ts
- apps/oidc-provider-nest/src/environments/environment.prod.ts
- apps/oidc-provider-nest/src/environments/environment.ts
- apps/oidc-provider-nest/src/main.ts
Loosened restrictions on dev for development/testing purposes and tightened on anything `tamu.edu` for production.
Addresses #215
> fix(idp-provider-nest): CORS policy restrictions

- apps/gisday-nest/project.json
Added generatePackageJson to project.json to fix builds not having a package.json.
> fix(gisday-nest): Added generatePackageJson to gisday-nest project.json

- apps/gisday-angular/src/environments/environment.dev.ts
- apps/gisday-nest/src/app/app.module.ts
- apps/gisday-nest/src/environments/environment.dev.ts
- libs/gisday/platform/data-api/src/lib/guards/auth.guard.ts
- Updated api_url in development environment (gisday-angular)
- Set globalPrefix to '' in development environment (gisday-nest)
- Set port to 27000 in development environment (gisday-nest)
- Fixed incorrect environment file used by app.module
- Updated JwksClient URL inside of AuthGuard (gisday-nest)
> fix(gisday-nest): Gisday environment updates

- apps/ues-operations-angular/src/environments/definitions.ts
- libs/ues/operations/ngx/src/lib/modules/map/map.module.ts
- libs/ues/operations/ngx/src/lib/modules/sidebar/sidebar.component.html
Implements the same bus route sidebar tab from aggie map that allows users to view the routes, time table, and bus position. 
Also includes a series of transportation services layers that can be useful for technicians on the field.
> feat(ues-operations): Adds important transportation layers and bus route tab to sidebar

- apps/ues-operations-angular/src/environments/definitions.ts
ues-arc.apogee.tamu.edu was not resolving and needed to switch to ues-arc.tamu.edu for layers and search sources.
> fix(ues-operations-angular): Updated definition hostnames

- apps/aggiemap-angular-e2e/src/integration/main-menu/sidebar-features.spec.ts
- apps/aggiemap-angular-e2e/src/support/resolutions.ts
- libs/common/ngx/ui/sidebar/src/lib/components/sidebar/sidebar.component.html
- libs/common/ngx/ui/sidebar/src/lib/components/tab/tab.component.html
Implemented testing of sidebar functionality. Tests focus on the usability of the sidebar and not the content inside of the side-menu. Content within the sidebar menu will be tested in their own respective files.
Testing of sidebar functionality includes:
- Closing sidebar when features tab is clicked
- Closing the sidebar when the directions and bus route tab are double clicked
- Opening the sidebar when the features tab is double clicked 
- Switching between sidebar menus
> e2e(angular-aggiemap): Implemented testing of sidebar features

- apps/aggiemap-angular/src/app/app.component.ts
- apps/aggiemap-angular/src/environments/notification-events.ts
- libs/aggiemap/ngx/core/src/lib/pages/map/map.component.html
- libs/aggiemap/ngx/core/src/lib/pages/map/map.component.ts
- libs/aggiemap/ngx/ui/shared/src/index.ts
- libs/aggiemap/ngx/ui/shared/src/lib/modules/modals/components/beta-prompt/beta-prompt.component.html
- libs/aggiemap/ngx/ui/shared/src/lib/modules/modals/components/beta-prompt/beta-prompt.component.scss
- libs/aggiemap/ngx/ui/shared/src/lib/modules/modals/components/beta-prompt/beta-prompt.component.spec.ts
- libs/aggiemap/ngx/ui/shared/src/lib/modules/modals/components/beta-prompt/beta-prompt.component.ts
- libs/aggiemap/ngx/ui/shared/src/lib/modules/modals/modals.module.ts
- libs/common/ngx/settings/src/lib/services/common-ngx-settings.service.ts
Adds a one-time notification prompting the existence of an aggiemap beta branch. This is meant for production to guide users into dev.aggiemap.tamu.edu. 
On the dev branch, users are now greeted with a modal popup describing the differences between prod and dev.
> feat(aggiemap-angular): Adds beta branch modal popup

- apps/cpa-angular/src/app/app.component.ts
- apps/cpa-angular/src/app/app.module.ts
- apps/cpa-angular/src/environments/environment.dev.ts
- apps/cpa-angular/src/environments/environment.prod.ts
- apps/cpa-angular/src/environments/environment.ts
- apps/cpa-nest/src/app/app.module.ts
- apps/cpa-nest/src/environments/environment.dev.ts
- apps/cpa-nest/src/environments/environment.prod.ts
- apps/cpa-nest/src/environments/environment.ts
- apps/cpa-nest/src/package.json
- libs/cpa/data-api/src/lib/modules/base/base.controller.ts
- libs/cpa/data-api/src/lib/modules/participants/participants.controller.ts
- libs/cpa/data-api/src/lib/modules/scenarios/scenarios.controller.ts
- libs/cpa/data-api/src/lib/modules/snapshots/snapshots.controller.ts
- libs/cpa/data-api/src/lib/modules/workshops/workshops.controller.ts
- libs/cpa/ngx/viewer/src/lib/cpa-ngx-viewer.module.ts
Integrates TAMU Geoservices SSO IdP
> feat(cpa-angular): IdP integration

- libs/common/nest/services/.babelrc
- libs/common/nest/services/.eslintrc.json
- libs/common/nest/services/README.md
- libs/common/nest/services/jest.config.js
- libs/common/nest/services/project.json
- libs/common/nest/services/src/index.ts
- libs/common/nest/services/src/lib/common-nest-services.module.ts
- libs/common/nest/services/src/lib/mailer/mailer.service.spec.ts
- libs/common/nest/services/src/lib/mailer/mailer.service.ts
- libs/common/nest/services/tsconfig.json
- libs/common/nest/services/tsconfig.lib.json
- libs/common/nest/services/tsconfig.spec.json
- tsconfig.base.json
- workspace.json
Generated boilerplate for:
- `libs/common/nest/services`
> feat(common-nest-services): Initial boilerplate

- apps/oidc-provider-nest/src/app/app.module.ts
- apps/oidc-provider-nest/src/environments/environment.dev.ts
- apps/oidc-provider-nest/src/environments/environment.prod.ts
- apps/oidc-provider-nest/src/environments/environment.ts
- apps/oidc-provider-nest/src/main.ts
- libs/common/nest/services/src/lib/mailer/mailer.service.ts
- libs/oidc/common/src/lib/modules/user/user.module.ts
- libs/oidc/common/src/lib/services/user/user.service.ts
- libs/oidc/provider/src/lib/controllers/interaction/interaction.controller.ts
- libs/oidc/provider/src/lib/modules/interaction/interaction.module.ts
This PR handles the integration of the MailService (created in PR #261) into the `oidc-provider-nest` application.
> feat(oidc-provider-nest): Integration of MailService

- apps/ues-operations-angular/src/environments/definitions.ts
This implements the SSO authorization for the IT fiber layers using the UES portal authentication.
> feat(ues-operations-angular): Changed fiber paths layer to load from UES hosted service

- CONTRIBUTING.md
- README.md
Initial contribution guideline documentation
> chore(docs): Initial contribution documentation

- libs/aggiemap/ngx/popups/src/lib/components/building/building-popup.component.html
- libs/aggiemap/ngx/popups/src/lib/components/building/building-popup.component.ts
Resolves #281 
The button in the building popup leads to a data portal that is not updated and thus inaccurate and is being removed for the time being.
> fix(aggiemap-angular): Remove proctor list button

- libs/aggiemap/ngx/core/src/lib/pages/map/map.component.ts
This condition was forgotten and causes the beta modal prompt to pop up on production environments.
Resolves #285
> fix(aggiemap-angular): Added condition to suppress beta prompt modal

- apps/gisday-angular/src/app/app.component.ts
Changed referenced environment file in `app.component` from hard coded .dev to the *changed at deployment* way.
Addresses issue #224
> fix(gisday-angular): Fixed hardcoded environment file

- libs/oidc/common/src/lib/controllers/user/user.controller.ts
Removed the controller level `AdminGuard` and instead put the guard on those routes that truly needed to be protected. 
Addresses issue #269.
> fix(oidc-provider-nest): Changed AdminGuard scope in user.controller
